/*
 *  netinet/tcp.h      TCP Protocol
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 *    Copyright (c) 2002-2010 Open Watcom Contributors. All Rights Reserved.
 *    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
#ifndef _NETINET_TCP_H_INCLUDED
#define _NETINET_TCP_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#pragma pack( __push, 4 )

/* TCP socket options */
#define TCP_NODELAY             1
#define TCP_MAXSEG              2
#define TCP_CORK                3
#define TCP_KEEPIDLE            4
#define TCP_KEEPINTVL           5
#define TCP_KEEPCNT             6
#define TCP_SYNCNT              7
#define TCP_LINGER2             8
#define TCP_DEFER_ACCEPT        9
#define TCP_WINDOW_CLAMP        10
#define TCP_INFO                11
#define TCP_QUICKACK            12

#pragma pack( __pop )

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* !_NETINET_TCP_H_INCLUDED */
