//
// XModDisp.HPP
//
// November 12, 1993
// WATCOM: October 3, 1994  BKH
// (c) Copyright 1993, Tachyon, Inc.  All rights reserved.
//
// Definitions for API calls specific to the graphics manager.
//
//----[]-------------------------------------------------------------


#ifndef	XModDisp_hpp
#define	XModDisp_hpp


#include "types.hpp"
#include "modex.hpp"


#define			INT_VIDEO	0x10		// Video Bios Interrupt

#endif
