/*
 *  bse.h       OS/2 Base include file for 16-bit development.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#define INCL_BASEINCLUDED

#ifdef INCL_BASE
  #define INCL_DOS
  #define INCL_SUB
  #define INCL_DOSERRORS
  #define INCL_DOSDEVICES
  #define INCL_DOSDEVIOCTL
#endif

#include <bsedos.h>
#include <bsesub.h>
#include <bseerr.h>

#if (defined(INCL_DOSDEVICES) || defined(INCL_DOSDEVIOCTL))
  #include <bsedev.h>
#endif
