/*
 *  pm.h        OS/2 Presentation Manager top level include file
 *              for 16-bit development.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef INCL_PM
    #define INCL_BITMAPFILEFORMAT
    #define INCL_DEV
    #define INCL_ERRORS
    #define INCL_GPI
    #define INCL_WIN
#endif

#include <pmwin.h>
#include <pmgpi.h>
#include <pmdev.h>

#ifdef INCL_BITMAPFILEFORMAT
#include <pmbitmap.h>
#endif
