/*
 *  pmbitmap.h  OS/2 Presentation Manager bitmap include file
 *              for 16-bit development.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define BFT_ICON          0x4349
#define BFT_BMAP          0x4d42
#define BFT_POINTER       0x5450
#define BFT_COLORICON     0x4943
#define BFT_COLORPOINTER  0x5043
#define BFT_BITMAPARRAY   0x4142

typedef struct _BITMAPFILEHEADER {
    USHORT usType;
    ULONG  cbSize;
    SHORT  xHotspot;
    SHORT  yHotspot;
    ULONG  offBits;
    BITMAPINFOHEADER bmp;
} BITMAPFILEHEADER, FAR *PBITMAPFILEHEADER;

typedef struct _BITMAPARRAYFILEHEADER {
    USHORT usType;
    ULONG  cbSize;
    ULONG  offNext;
    USHORT cxDisplay;
    USHORT cyDisplay;
    BITMAPFILEHEADER bfh;
} BITMAPARRAYFILEHEADER, FAR *PBITMAPARRAYFILEHEADER;

#ifdef __cplusplus
} /* extern "C" */
#endif
