/*
 *  ole2ver.h   Object Linking and Embedding (OLE) 2.0 version numbers
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

/* OLE 2.0 version numbers */
#define rmj         0
#define rmm         23
#define rup         700
#define szVerName   ""
#define szVerUser   "Y-OLEBLD"
