/*
 *  sys/lipcpar.h
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _SYS_LIPCPAR_H
#define _SYS_LIPCPAR_H

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#define LIPCCTL_INETCFG      60
#define LIPCCTL_INETVER      61
#define LIPCCTL_ST_SENDSPACE 62
#define LIPCCTL_ST_RECVSPACE 63
#define LIPCCTL_DG_SENDSPACE 64
#define LIPCCTL_DG_RECVSPACE 65

#endif
