/*
 *  ntddbeep.h  Beep device I/O control codes
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _NTDDBEEP_
#define _NTDDBEEP_

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Beep device name */
#define DD_BEEP_DEVICE_NAME     "\\Device\\Beep"
#define DD_BEEP_DEVICE_NAME_U   L"\\Device\\Beep"

/* Beep device I/O control codes */
#define IOCTL_BEEP_SET \
    CTL_CODE( FILE_DEVICE_BEEP, 0, METHOD_BUFFERED, FILE_ANY_ACCESS )

/* Beep frequency special values */
#define BEEP_FREQUENCY_MINIMUM  0x0025
#define BEEP_FREQUENCY_MAXIMUM  0x7FFF

/* Beep set parameters */
typedef struct _BEEP_SET_PARAMETERS {
    ULONG   Frequency;
    ULONG   Duration;
} BEEP_SET_PARAMETERS;
typedef BEEP_SET_PARAMETERS *PBEEP_SET_PARAMETERS;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* _NTDDBEEP_ */
