/*
 *  mciapi.h    Multimedia Control Interface High-level constants and prototypes.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef __MCIAPI_H__
#define __MCIAPI_H__

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define MMIO_FE_FINDFIRST   1
#define MMIO_FE_FINDNEXT    2
#define MMIO_FE_FINDEND     3
#define MMIO_FE_FINDELEMENT 4

#define MMIO_RE_COMPACT     1

#define MCI_OWNERISPARENT   0x0001
#define MCI_STOPACTIVE      0x0002
#define MCI_ASYNCRENDEZVOUS 0x0004
#define MCI_RENDEZVOUS      0x0008
#define MCI_ASYNC           0x0010
#define MCI_REPEAT          0x0020
#define MCI_STOPONSUSPEND   0x0040

ULONG EXPENTRY mciPlayFile(HWND,PSZ,ULONG,PSZ,HWND);
ULONG EXPENTRY mciPlayResource(HWND,HMODULE,ULONG,ULONG,ULONG,PSZ,HWND);
ULONG EXPENTRY mciRecordAudioFile(HWND,PSZ,PSZ,ULONG);

ULONG EXPENTRY mmioFindElement(ULONG,PSZ,ULONG,PSZ,ULONG);
ULONG EXPENTRY mmioRemoveElement(PSZ,ULONG);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
