/*
 *  os2.h        OS/2 top level include file for 32-bit development.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef __OS2_H__
#define __OS2_H__

#define OS2_INCLUDED

#ifdef _M_I86
#error This os2.h is for 32-bit development only!
#endif

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include <os2def.h>
#include <bse.h>
#include <pm.h>

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
