/*
 *  pm.h        OS/2 Presentation Manager top level include file
 *              for 32-bit development.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef INCL_PM
  #define INCL_AVIO
  #define INCL_DEV
  #define INCL_ERRORS
  #define INCL_GPI
  #define INCL_WIN
  #define INCL_SPL
#endif

#include <pmwin.h>
#include <pmgpi.h>
#include <pmdev.h>
#include <pmwp.h>
#include <pmstddlg.h>

#ifdef INCL_AVIO
  #include <pmavio.h>
#endif

#ifdef INCL_SPL
  #include <pmspl.h>
#endif
