/*
 *  utils.h     Declaration of the rexec function.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _UTILS_H_
#define _UTILS_H_

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

int _System rexec(char **, int, char *, char *, char *, int *);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
