/*
 *  arpa/inet.h      Internet address manipulation routines
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 *    Copyright (c) 2002-2010 Open Watcom Contributors. All Rights Reserved.
 *    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
#ifndef _ARPA_INET_H_INCLUDED
#define _ARPA_INET_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifndef _COMDEF_H_INCLUDED
 #include <_comdef.h>
#endif

#ifndef __TYPES_H_INCLUDED
 #include <sys/types.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#pragma pack( __push, 4 )

_WCRTLINK int               inet_aton( const char *cp, struct in_addr *__inp );
_WCRTLINK uint32_t          inet_addr( const char *__cp );
_WCRTLINK uint32_t          inet_network( const char *__cp );
_WCRTLINK char              *inet_ntoa( struct in_addr in );
_WCRTLINK struct in_addr    inet_makeaddr( int net, int __host );
_WCRTLINK uint32_t          inet_lnaof( struct in_addr __in );
_WCRTLINK uint32_t          inet_netof( struct in_addr __in );

#pragma pack( __pop )

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* !_ARPA_INET_H_INCLUDED */

